### ISSUE TITLE
calling connection.close() does not release the connection

### ISSUE THREAD

**Issue by HenrikHL** [pgjdbc/r2dbc-postgresql#314]
#### Versions

- Driver:r2dbc-postgresql 0.8.4.RELEASE
- Database: PostGres
- Java: 11
- OS: Windows 10 64bit

#### Current Behavior

After making 10 database requests my application hangs

<details>
<summary>Stack trace</summary>

After shutting my application the following stacktrace occurs:

```
Disconnected from the target VM, address: '127.0.0.1:60158', transport: 'socket'
2020-08-13 12:14:02.615 ERROR 16460 --- [extShutdownHook] dk.asseco.dcc.controller.BaseController  : CustomerController error!

reactor.pool.PoolShutdownException: Pool has been shut down
	at reactor.pool.SimplePool.doAcquire(SimplePool.java:131) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler dk.asseco.dcc.controller.CustomerController#findAll(ServerHttpResponse, ServerHttpRequest) [DispatcherHandler]
Stack trace:
		at reactor.pool.SimplePool.doAcquire(SimplePool.java:131) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:363) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:130) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:163) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.pool.SimplePool$QueueBorrowerMono.subscribe(SimplePool.java:381) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:110) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:94) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:408) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.pool.SimpleFifoPool.lambda$disposeLater$0(SimpleFifoPool.java:89) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8325) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1679) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at io.r2dbc.pool.ConnectionPool.dispose(ConnectionPool.java:218) ~[r2dbc-pool-0.8.3.RELEASE.jar:0.8.3.RELEASE]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:142) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]

2020-08-13 12:14:02.634 ERROR 16460 --- [extShutdownHook] a.w.r.e.AbstractErrorWebExceptionHandler : [1ef2fab2]  500 Server Error for HTTP null "/customers?sort=name"

reactor.pool.PoolShutdownException: Pool has been shut down
	at reactor.pool.SimplePool.doAcquire(SimplePool.java:131) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler dk.asseco.dcc.controller.CustomerController#findAll(ServerHttpResponse, ServerHttpRequest) [DispatcherHandler]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2ResourceServerSpec$BearerTokenAuthenticationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.csrf.CsrfWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP null "/customers?sort=name" [ExceptionHandlingWebHandler]
Stack trace:
		at reactor.pool.SimplePool.doAcquire(SimplePool.java:131) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:363) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:130) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:163) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.pool.SimplePool$QueueBorrowerMono.subscribe(SimplePool.java:381) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:110) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:94) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:227) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:214) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:408) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.pool.SimpleFifoPool.lambda$disposeLater$0(SimpleFifoPool.java:89) ~[reactor-pool-0.1.5.RELEASE.jar:0.1.5.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8325) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4213) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.publisher.Mono.block(Mono.java:1679) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at io.r2dbc.pool.ConnectionPool.dispose(ConnectionPool.java:218) ~[r2dbc-pool-0.8.3.RELEASE.jar:0.8.3.RELEASE]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
		at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:142) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
		at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]


Process finished with exit code 130
```
</details>
 
#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
I have created the following code in my Repository class:

public class CustomerRepositoryImpl<Customer> {

    private ConnectionFactory connectionFactory;

    public CustomerRepositoryImpl(ConnectionFactory connectionFactory) {
        this.connectionFactory = connectionFactory;
    }

    public Flux<Customer> findAllCustomers() {
        return Mono.from(connectionFactory.create())
                .flatMap(connection ->
                        Mono.from(
                                connection.createStatement("SELECT * FROM master_customer")
                                        .execute())
                                .doFinally((st) -> connection.close())
                )
                .flatMapMany(result -> Flux.from(result.map((row, meta) -> {
                    // I am aware that this just creates empty instances of Customer
                    return new Customer();
                })));
    }
}
```

</details>

#### Expected behavior/code

I would expect the connection to be released once the request is finished. After calling the above code 10 times the system hangs (an infinite loop somewhere...?)

**Comment by mp911de** [comment]
Please note that `.doFinally((st) -> connection.close())` doesn't have an effect at all. You need to subscribe to the `Publisher` returned from `close()`.

**Comment by mp911de** [comment]
Closing this ticket since the issue isn't related to our driver.
