### ISSUE TITLE
Driver fails with `Cannot connect to localhost` on Github Actions

### ISSUE THREAD

**Issue by dstepanov** [pgjdbc/r2dbc-postgresql#430]
0.8.4

```
io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost:49165
  |                |          |         	at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:218)
  |                |          |         	at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3323)
  |                |          |         	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
  |                |          |         	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
  |                |          |         	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
  |                |          |         	at reactor.core.publisher.Operators.error(Operators.java:196)
  |                |          |         	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
  |                |          |         	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
  ```

The solution is to set system property `java.net.preferIPv4Stack` to `true`

https://github.com/micronaut-projects/micronaut-data/pull/1095

**Comment by mp911de** [comment]
I tried to trace what's happening as we had similar reports before (see #397) and we deliberately didn't run integration tests for the driver. I do not know what changed or what's the difference, but I wasn't able to reproduce the issue (https://github.com/sampledump/r2dbc-actions/actions) even with trying to replicate dependency versions and the Postgres container version. 

Can you help me out with a failed build on your side that has [trace logging enabled](https://github.com/sampledump/r2dbc-actions/blob/main/src/test/resources/logback-test.xml#L27)? I'd be interested to learn what's happening and why the progress gets stuck.

**Comment by dstepanov** [comment]
I will create a PR

**Comment by dstepanov** [comment]
https://github.com/micronaut-projects/micronaut-data/pull/1101

**Comment by dstepanov** [comment]
You can check https://github.com/micronaut-projects/micronaut-data/pull/1101/checks?check_run_id=3144823164

**Comment by mp911de** [comment]
Thanks a lot, that was helpful. According to the log, the Postgres service listens only on the IPv4 interface: `Connection refused: localhost/[0:0:0:0:0:0:0:1]:49168`

Actually, I was expecting a bug in the connectivity but likely, it's as trivial as a dual-stack system with listening only on the IPv4 stack. A few log events below, there was a successful connect to the IPv4 address.

I'm not sure how to fix the issue properly, whether it's a Testcontainers or a GitHub issue therefore the proposed workaround preferring IPv4 is still valid.

```
  io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost/<unresolved>:49168
      at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:218)
      at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3323)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
      at reactor.core.publisher.Operators.error(Operators.java:196)
      at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
      at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
      at reactor.core.publisher.Operators.error(Operators.java:196)
      at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
      at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
      at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
      at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
      at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.onError(MonoDelayUntil.java:176)
      at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
      at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:189)
      at reactor.netty.resources.NewConnectionProvider$DisposableConnect.onError(NewConnectionProvider.java:139)
      at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
      at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
      at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:464)
      at reactor.netty.transport.TransportConnector$MonoChannelPromise$1.tryFailure(TransportConnector.java:515)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:637)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:656)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530)
      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:832)
  Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/[0:0:0:0:0:0:0:1]:49168

  Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
      at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
      at io.netty.channel.unix.Socket.finishConnect(Socket.java:252)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650)
      at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530)
      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:832)


  15:21:16.930 [reactor-tcp-epoll-4] DEBUG i.r.p.client.ReactorNettyClient - [cid: 0x60d][id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] Request:  StartupMessage{applicationName='r2dbc-postgresql', database='test', username='test', options='{statement_timeout=5s}'}
  15:21:16.930 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] WRITE: 161B
           +-------------------------------------------------+
           |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
  +--------+-------------------------------------------------+----------------+
  |00000000| 00 00 00 a1 00 03 00 00 75 73 65 72 00 74 65 73 |........user.tes|
  |00000010| 74 00 64 61 74 61 62 61 73 65 00 74 65 73 74 00 |t.database.test.|
  |00000020| 61 70 70 6c 69 63 61 74 69 6f 6e 5f 6e 61 6d 65 |application_name|
  |00000030| 00 72 32 64 62 63 2d 70 6f 73 74 67 72 65 73 71 |.r2dbc-postgresq|
  |00000040| 6c 00 63 6c 69 65 6e 74 5f 65 6e 63 6f 64 69 6e |l.client_encodin|
  |00000050| 67 00 75 74 66 38 00 44 61 74 65 53 74 79 6c 65 |g.utf8.DateStyle|
  |00000060| 00 49 53 4f 00 65 78 74 72 61 5f 66 6c 6f 61 74 |.ISO.extra_float|
  |00000070| 5f 64 69 67 69 74 73 00 32 00 54 69 6d 65 5a 6f |_digits.2.TimeZo|
  |00000080| 6e 65 00 45 74 63 2f 55 54 43 00 73 74 61 74 65 |ne.Etc/UTC.state|
  |00000090| 6d 65 6e 74 5f 74 69 6d 65 6f 75 74 00 35 73 00 |ment_timeout.5s.|
  |000000a0| 00                                              |.               |
  +--------+-------------------------------------------------+----------------+
  15:21:16.930 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] FLUSH
  15:21:16.931 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] READ: 13B
           +-------------------------------------------------+
           |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
  +--------+-------------------------------------------------+----------------+
  |00000000| 52 00 00 00 0c 00 00 00 05 93 94 32 61          |R..........2a   |
  +--------+-------------------------------------------------+----------------+
  15:21:16.931 [reactor-tcp-epoll-4] DEBUG i.r.p.client.ReactorNettyClient - [cid: 0x60d][id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] Response: AuthenticationMD5Password{salt=java.nio.HeapByteBuffer[pos=0 lim=4 cap=4]}
  15:21:16.931 [reactor-tcp-epoll-4] DEBUG i.r.p.client.ReactorNettyClient - [cid: 0x60d][id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] Request:  PasswordMessage{password='...'}
  15:21:16.931 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] WRITE: 41B
           +-------------------------------------------------+
           |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
  +--------+-------------------------------------------------+----------------+
  |00000000| 70 00 00 00 28 6d 64 35 61 33 33 63 30 31 34 34 |p...(md5a33c0144|
  |00000010| 64 36 32 61 66 35 62 65 35 30 61 37 39 66 35 64 |d62af5be50a79f5d|
  |00000020| 34 64 37 62 39 38 31 35 00                      |4d7b9815.       |
  +--------+-------------------------------------------------+----------------+
  15:21:16.931 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] FLUSH
  15:21:16.931 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] READ COMPLETE
  15:21:16.932 [reactor-tcp-epoll-4] TRACE i.r.p.client.ReactorNettyClient - [id: 0x3014fb85, L:/127.0.0.1:57098 - R:localhost/127.0.0.1:49168] READ: 360B
           +-------------------------------------------------+
           |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
  +--------+-------------------------------------------------+----------------+
  |00000000| 52 00 00 00 08 00 00 00 00 53 00 00 00 26 61 70 |R........S...&ap|
  |00000010| 70 6c 69 63 61 74 69 6f 6e 5f 6e 61 6d 65 00 72 |plication_name.r|
  |00000020| 32 64 62 63 2d 70 6f 73 74 67 72 65 73 71 6c 00 |2dbc-postgresql.|
  |00000030| 53 00 00 00 19 63 6c 69 65 6e 74 5f 65 6e 63 6f |S....client_enco|
  |00000040| 64 69 6e 67 00 55 54 46 38 00 53 00 00 00 17 44 |ding.UTF8.S....D|
  |00000050| 61 74 65 53 74 79 6c 65 00 49 53 4f 2c 20 4d 44 |ateStyle.ISO, MD|
  |00000060| 59 00 53 00 00 00 19 69 6e 74 65 67 65 72 5f 64 |Y.S....integer_d|
  |00000070| 61 74 65 74 69 6d 65 73 00 6f 6e 00 53 00 00 00 |atetimes.on.S...|
  |00000080| 1b 49 6e 74 65 72 76 61 6c 53 74 79 6c 65 00 70 |.IntervalStyle.p|
  |00000090| 6f 73 74 67 72 65 73 00 53 00 00 00 14 69 73 5f |ostgres.S....is_|
  |000000a0| 73 75 70 65 72 75 73 65 72 00 6f 6e 00 53 00 00 |superuser.on.S..|
  |000000b0| 00 19 73 65 72 76 65 72 5f 65 6e 63 6f 64 69 6e |..server_encodin|
  |000000c0| 67 00 55 54 46 38 00 53 00 00 00 33 73 65 72 76 |g.UTF8.S...3serv|
  |000000d0| 65 72 5f 76 65 72 73 69 6f 6e 00 31 30 2e 31 37 |er_version.10.17|
  |000000e0| 20 28 44 65 62 69 61 6e 20 31 30 2e 31 37 2d 31 | (Debian 10.17-1|
  |000000f0| 2e 70 67 64 67 39 30 2b 31 29 00 53 00 00 00 1f |.pgdg90+1).S....|
  |00000100| 73 65 73 73 69 6f 6e 5f 61 75 74 68 6f 72 69 7a |session_authoriz|
  |00000110| 61 74 69 6f 6e 00 74 65 73 74 00 53 00 00 00 23 |ation.test.S...#|
  |00000120| 73 74 61 6e 64 61 72 64 5f 63 6f 6e 66 6f 72 6d |standard_conform|
  |00000130| 69 6e 67 5f 73 74 72 69 6e 67 73 00 6f 6e 00 53 |ing_strings.on.S|
  |00000140| 00 00 00 15 54 69 6d 65 5a 6f 6e 65 00 45 74 63 |....TimeZone.Etc|
  |00000150| 2f 55 54 43 00 4b 00 00 00 0c 00 00 00 53 8f 8e |/UTC.K.......S..|
  |00000160| bd 92 5a 00 00 00 05 49                         |..Z....I        |
  +--------+-------------------------------------------------+----------------+
```
